#!/bin/bash 
echo "### GENERATING SWAG FILES..."
swag init --md docs/md_endpoints
echo "### BUILDING PROJECT..."
go build -o dapp
echo "### SETTING ENVIROMENT VARIABLES..."
source ./setenv.sh
echo "### RUNNING POSGRESQL Docker container..."
docker-compose -f docker-compose-extra.yml up -d
echo "### RUNNING PROJECT..."
./dapp
